# Generated by Django 6.0.3 on 2026-05-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_access_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
