# Generated by Django 6.0.3 on 2026-05-16 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_school_admin_class'),
        ('students', '0006_student_role_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_fk',
            field=models.ForeignKey(blank=True, help_text='The auto-generated class this student belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schools.class'),
        ),
    ]
