# Generated by Django 6.0.3 on 2026-05-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('course_opened', 'Course opened'), ('lesson_completed', 'Lesson completed'), ('quiz_submitted', 'Quiz submitted'), ('assignment_submitted', 'Assignment submitted'), ('attendance_marked', 'Attendance marked')], max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='core_activi_event_t_60cf36_idx'), models.Index(fields=['actor', 'created_at'], name='core_activi_actor_i_cbcc7a_idx')],
            },
        ),
    ]
