# Generated by Django 6.0.3 on 2026-05-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_enrollmentcode_enrollmentcodeevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
