# Generated by Django 6.0.3 on 2026-05-16 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options_user_unique_email_per_school'),
        ('schools', '0006_school_admin_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='schools_school',
            field=models.OneToOneField(blank=True, help_text='Bridge to the canonical seeded school model.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_school', to='schools.school'),
        ),
    ]
