# Generated by Django 6.0.3 on 2026-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprecord',
            name='reset_token_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
