# Generated by Django 6.0.3 on 2026-05-12 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='xptransaction',
            old_name='xp',
            new_name='xp_amount',
        ),
        migrations.AddField(
            model_name='xptransaction',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xptransaction',
            name='source_type',
            field=models.CharField(blank=True, choices=[('lesson', 'Lesson'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('task', 'Task'), ('streak', 'Streak')], max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='xptransaction',
            constraint=models.UniqueConstraint(fields=('student', 'source_type', 'source_id'), name='unique_xp_source'),
        ),
    ]
