# Generated by Django 6.0.3 on 2026-05-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='target_capacity',
            field=models.PositiveIntegerField(default=35, help_text='Target maximum enrollment'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled lesson end time', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled lesson start time', null=True),
        ),
    ]
