# Generated by Django 6.0.3 on 2026-05-07 14:13

from django.db import migrations


def copy_enrollments(apps, schema_editor):
    Enrollment = apps.get_model("courses", "Enrollment")
    StudentCourse = apps.get_model("courses", "StudentCourse")
    for e in Enrollment.objects.iterator():
        StudentCourse.objects.get_or_create(
            course=e.course,
            student=e.student,
            defaults={"is_active": True, "enrolled_at": e.enrolled_at},
        )


def reverse_copy(apps, schema_editor):
    StudentCourse = apps.get_model("courses", "StudentCourse")
    StudentCourse.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_grade_courseprogress_studentcourse"),
    ]

    operations = [
        migrations.RunPython(copy_enrollments, reverse_code=reverse_copy),
    ]
