# Generated by Django 6.0.3 on 2026-05-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_migrate_enrollment_to_studentcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
