# Generated by Django 6.0.3 on 2026-05-07 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_delete_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_duration_seconds', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_activities', to='courses.lesson')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Activity',
                'verbose_name_plural': 'Lesson Activities',
                'indexes': [models.Index(fields=['lesson', 'completed'], name='courses_les_lesson__937d7f_idx')],
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
