# Generated by Django 6.0.3 on 2026-05-15 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_answeroption_question_quizsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, upload_to='lessons/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'avi', 'mkv', 'wmv', 'flv', '3gp'])]),
        ),
    ]
