# Generated by Django 6.0.3 on 2026-05-16 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lesson_video_file'),
        ('schools', '0006_school_admin_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(help_text='The school this course belongs to (populated from grade.school).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schools.school'),
        ),
    ]
