# Generated by Django 6.0.3 on 2026-05-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='late_penalty_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher_file',
            field=models.FileField(blank=True, upload_to='assignment_files/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='xp_reward',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
