# Generated by Django 6.0.3 on 2026-05-16 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_rename_global_grades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='The school admin user for this school.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_schools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'grade'], name='schools_cla_school__07a64d_idx')],
                'unique_together': {('school', 'grade', 'name')},
            },
        ),
    ]
