# Generated by Django 6.0.3 on 2026-05-07 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_quiz_quizattempt_quiz_courses_qui_course__ac0918_idx_and_more'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_content_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('assignment_created', 'Assignment Created'), ('submission_created', 'Submission Created'), ('submission_graded', 'Submission Graded'), ('attendance_marked', 'Attendance Marked'), ('enrollment_created', 'Enrollment Created'), ('lesson_created', 'Lesson Created'), ('quiz_created', 'Quiz Created')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_course'], name='notificatio_related_9e7856_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event_type', 'created_at'], name='notificatio_event_t_4562fd_idx'),
        ),
    ]
