# Generated by Django 6.0.3 on 2026-05-10 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_quiz_quizattempt_quiz_courses_qui_course__ac0918_idx_and_more'),
        ('notifications', '0002_notification_related_content_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('assignment_created', 'Assignment Created'), ('submission_created', 'Submission Created'), ('submission_graded', 'Submission Graded'), ('attendance_marked', 'Attendance Marked'), ('enrollment_created', 'Enrollment Created'), ('lesson_created', 'Lesson Created'), ('quiz_created', 'Quiz Created'), ('quiz_deadline', 'Quiz Deadline Passed'), ('grade_updated', 'Grade Updated')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['parent', 'is_read'], name='notificatio_parent__752032_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('parent', 'event_type', 'reference_id'), name='unique_parent_notification'),
        ),
    ]
